import AboutUs from '@/modules/components/AboutUs';
import { ConfirmationCard } from '@/modules/components/ConfirmationCard';
import Gift from '@/modules/components/Gift';
import { ImageCard } from '@/modules/components/ImageCard';
import { NavigationHeader } from '@/modules/components/NavigationHeader';
import { Presentation } from '@/modules/components/Presentation';
import SongsSugestions from '@/modules/components/SongsSugestions';
import { WelcomeTextCard } from '@/modules/components/WelcomeTextCard';
import bg from '@/public/images/tile-background.png';
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>¡Nos casamos!</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, height=device-height, initial-scale=1"/>
                <link rel="icon"
                      href="/favicon.ico"/>
            </Head>
            <div className='flex flex-col items-center bg-white'
                style={{
                backgroundImage: `url(${bg.src})`,
                backgroundRepeat: 'repeat',
            }}>
                <main className='flex flex-col'>
                    <div className="flex flex-col items-center font-sans max-w-5xl">
                        <NavigationHeader/>
                        <Presentation/>
                        <WelcomeTextCard/>
                        <AboutUs/>
                        <div className='w-full flex flex-col lg:flex-row'>
                            <ImageCard
                                imageSrc={`${process.env.NEXT_PUBLIC_IMAGES_ROUTE}/iglesiacapuccino.svg`}
                                srcUrl='https://www.google.com.ar/maps/place/Sauron+Adventure+%26+Homes/@-31.4245626,-64.5901904,15z/data=!4m6!3m5!1s0x942d69b032d83063:0x84f11aa1a57f6d4d!8m2!3d-31.4245626!4d-64.5901904!16s%2Fg%2F11h8bc979v?entry=ttu'
                                imageAlt='Imagen del castillo de bellver, donde nos casamos'
                                title='LA IGLESIA'
                                subtitle='16:00 - Iglesia los Capuccinos'/>
                            <ImageCard
                                imageSrc={`${process.env.NEXT_PUBLIC_IMAGES_ROUTE}/sauron.svg`}
                                srcUrl='https://www.google.com.ar/maps/place/Sauron+Adventure+%26+Homes/@-31.4245626,-64.5901904,15z/data=!4m6!3m5!1s0x942d69b032d83063:0x84f11aa1a57f6d4d!8m2!3d-31.4245626!4d-64.5901904!16s%2Fg%2F11h8bc979v?entry=ttu'
                                imageAlt='Imagen del Lume, donde celebramos el banquete'
                                title='EL CIVIL Y LA FIESTA'
                                subtitle='17:30 - Sauron'/>
                        </div>
                        <ConfirmationCard/>
                        <Gift/>
                        <SongsSugestions/>
                    </div>
                </main>
            </div>
        </>
    )
}
