import AboutUs from '@/modules/components/AboutUs';
import { ConfirmationCard } from '@/modules/components/ConfirmationCard';
import Gift from '@/modules/components/Gift';
import { ImageCard } from '@/modules/components/ImageCard';
import { NavigationHeader } from '@/modules/components/NavigationHeader';
import { Presentation } from '@/modules/components/Presentation';
import SongsSugestions from '@/modules/components/SongsSugestions';
import { WelcomeTextCard } from '@/modules/components/WelcomeTextCard';
import Head from 'next/head'

const bg = '/images/tile-background.png';

export default function Home() {
    return (
        <>
            <Head>
                <title>¡Nos casamos!</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, height=device-height, initial-scale=1"/>
                <link rel="icon"
                      href="/favicon.ico"/>
            </Head>
            <div className='flex flex-col items-center bg-white'
                style={{
                backgroundImage: `url(${bg})`,
                backgroundRepeat: 'repeat',
            }}>
                <main className='flex flex-col'>
                    <div className="flex flex-col items-center font-sans max-w-5xl">
                        <NavigationHeader/>
                        <Presentation/>
                        <WelcomeTextCard/>
                        <AboutUs/>
                        <div className='w-full flex flex-col lg:flex-row'>
                            <ImageCard
                                imageSrc={`${process.env.NEXT_PUBLIC_IMAGES_ROUTE}/iglesiaaltagracia.svg`}
                                srcUrl='https://www.google.com.ar/maps/place/Iglesia+Nuestra+Se%C3%B1ora+de+La+Merced/@-31.6579377,-64.4363533,17z/data=!3m1!4b1!4m6!3m5!1s0x942d50ca819f15c9:0xcb26e6601493160!8m2!3d-31.6579377!4d-64.4346727!16s%2Fg%2F1tdzxtmk?entry=ttu'
                                imageAlt='Iglesia de alta gracia, donde nos casamos'
                                title='LA IGLESIA'
                                subtitle='16:00 - Nuestra Sra de La Merced  '/>
                            <ImageCard
                                imageSrc={`${process.env.NEXT_PUBLIC_IMAGES_ROUTE}/laquinta.svg`}
                                srcUrl='https://www.google.com.ar/maps/dir//RP+E96+KM+20,5,+C%C3%B3rdoba/@-31.5946051,-64.5230104,12.91z/data=!4m8!4m7!1m0!1m5!1m1!1s0x9432993754be98fb:0x3305d1df5c8ada82!2m2!1d-64.4893622!2d-31.5954508?entry=ttu'
                                imageAlt='La quinta casa de montaña'
                                title='EL CIVIL Y LA FIESTA'
                                subtitle='17:30 - La Quinta Casa de Montaña'/>
                        </div>
                        <ConfirmationCard/>
                        <Gift/>
                        <SongsSugestions/>
                    </div>
                </main>
            </div>
        </>
    )
}